[package]
name = "htrs"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.14"
rstml-component = "0.2.1"
serde = "1.0.188"
serde_derive = "1.0.188"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
